# Generated by Django 4.0.4 on 2022-05-29 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('employee_profile_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='users.employerprofile')),
                ('status', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='approvals.approvalstatus')),
            ],
        ),
    ]
