# Generated by Django 4.0.4 on 2022-05-29 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('cvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='worker_profile',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='users.workerprofile'),
        ),
    ]
