"""
Django settings for BestJob project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@+k6dcw1r6e1^w3ywn94wmav3*l^6(ivj_ljsynrye((n6gc31'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap_datepicker_plus',
    'haystack',
    'approvals',
    'cvs',
    'news',
    'search',
    'users',
    'vacancies',
    'relations',
    'widget_tweaks',
    'favorites',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BestJob.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Контекстный процессор для footer
                'users.context_processors.footer_lists',
                # Контекстный процессор для ролей
                'users.context_processors.roles'
            ],
            'libraries': {
                'extra_tags': 'favorites.context_processors',
            }
        },
    },
]

WSGI_APPLICATION = 'BestJob.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'bestjob',
#         'USER': 'postgres'
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ru-Ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = (BASE_DIR / 'static',)
# STATIC_ROOT = '/var/www/bestjob/static'
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Пути для сохранения изображений при локальной работе. В BestJob.urls добавлено:
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# модель юзера у нас cвоя, поэтому добавляем в настройки

AUTH_USER_MODEL = "users.User"

# наша страница после логина
LOGIN_REDIRECT_URL = 'index'

# время действия ключа подтверждения email [ч]
USER_EMAIL_KEY_LIFETIME = 48

# настройки для подтверждения email
# для получения в термина ссылки (linux):  sudo python3 -m smtpd -n -c DebuggingServer localhost:25
# для получения в термина ссылки (windows):  python -m smtpd -n -c DebuggingServer localhost:25
DOMAIN_NAME = '127.0.0.1:8000'

if os.getenv('EMAIL_HOST'):
    EMAIL_HOST = os.getenv('EMAIL_HOST')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT'))
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
    EMAIL_USE_TLS = True if os.getenv('EMAIL_USE_TLS') == 'True' else False
    EMAIL_USE_SSL = True if os.getenv('EMAIL_USE_SSL') == 'True' else False
else:
    EMAIL_HOST = 'localhost'
    EMAIL_PORT = 25
    EMAIL_USER_SSL = True if os.getenv('EMAIL_USER_SSL') == 'True' else False
    EMAIL_HOST_USER, EMAIL_HOST_PASSWORD = None, None

import os

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': os.path.join(os.path.dirname(__file__), 'whoosh_index'),
    },
}

HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

NEWS_BODY_LEN_ON_NEWS_LIST = 297

HAYSTACK_SEARCH_RESULTS_PER_PAGE = 4  # пагинация. кол-во на странице (HAYSTACK)


# Константы ролей пользователей.
class UserRole:
    # Модератор.
    MODERATOR = 1
    # Работодатель.
    EMPLOYER = 2
    # Соискатель.
    WORKER = 3


# Константы статусов откликов и приглашений.
class RelationStatuses:
    # Приглашение.
    INVITATION = 1
    # Отклик.
    RESPONSE = 2
    # Приглашение не просмотрено.
    INVITATION_NOT_VIEWED = 3
    # Резюме не просмотрено.
    RESUME_NOT_VIEWED = 4
    # Приглашение просмотрено.
    INVITATION_VIEWED = 5
    # Резюме просмотрено.
    RESUME_VIEWED = 6
    # Отказ.
    REFUSAL = 7
    # Встреча согласована.
    MEETING_AGREED = 8
